channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.6
  - pytorch-cpu
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - requests
  - pip
  - tqdm
  - spacy
  - scrapy
  - selenium
  - bs4
  - webdriver-manager
  - pip:
    - transformers
    - tweepy
# For development
  - ipykernel
  - jupyter
  - black
  - pylint
  - flake8
  - pytest
  - pyyaml