channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.6
  - cudatoolkit=10.2
  - pytorch
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - requests
  - pip
  - tqdm
  - spacy
  - cupy
  - scrapy
  - selenium
  - bs4
  - webdriver-manager
  - pip:
    - transformers
    - tweepy
    - pre-commit
# For development
  - ipykernel
  - jupyter
  - black
  - pylint
  - flake8
  - pytest
  - pyyaml